In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/PRISMA Grey Literature - GitHub.csv')

In [4]:
df.shape

(2072, 8)

In [5]:
df.head()

,type,query,name,url,description,stars,language,date
0,repository,"""open source"" ""AI"" ""security"" stars:>50 in:nam...",ollama/ollama,https://github.com/ollama/ollama,"Get up and running with OpenAI gpt-oss, DeepSe...",157794.0,Go,2025-12-17T14:39:14Z
1,repository,"""open source"" ""AI"" ""security"" stars:>50 in:nam...",langflow-ai/langflow,https://github.com/langflow-ai/langflow,Langflow is a powerful tool for building and d...,141368.0,Python,2025-12-17T15:02:57Z
2,repository,"""open source"" ""AI"" ""security"" stars:>50 in:nam...",langgenius/dify,https://github.com/langgenius/dify,Production-ready platform for agentic workflow...,121990.0,TypeScript,2025-12-17T15:01:35Z
3,repository,"""open source"" ""AI"" ""security"" stars:>50 in:nam...",open-webui/open-webui,https://github.com/open-webui/open-webui,"User-friendly AI Interface (Supports Ollama, O...",118050.0,Svelte,2025-12-17T14:27:03Z
4,repository,"""open source"" ""AI"" ""secure"" stars:>50 in:name,...",microsoft/generative-ai-for-beginners,https://github.com/microsoft/generative-ai-for...,"21 Lessons, Get Started Building with Generati...",103933.0,Jupyter Notebook,2025-12-17T14:47:37Z

In [6]:
df.isna().sum()

type            0
query           0
name            0
url             0
description     0
stars          12
language       12
date           12
dtype: int64

In [7]:
df2 = df.dropna()

In [8]:
df2.shape

(2060, 8)

In [11]:
df2['text_all'] = (
    df2['name'].fillna('') + ' ' +
    df2['description'].fillna('')
).str.lower()
#+ ' ' +
    #df2['query'].fillna('')

/tmp/ipykernel_683/294186043.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['text_all'] = (

In [12]:
# AI-related keywords
ai_keywords = [
    "ai", "artificial intelligence",
    "machine learning", "ml",
    "deep learning",
    "neural network", "neural networks",
    "large language model", "llm",
    "generative ai",
    "foundation model"
]

# Security-related keywords
security_keywords = [
    "security", "secure",
    "vulnerability", "vulnerabilities", "vulnerable",
    "exploit", "attacker", "attackers", "attack", "attacks",
    "adversarial",           # often used in "adversarial attacks"
    "penetration testing", "pentest", "pen-test",
    "malware", "threat", "threats",
    "xss", "sql injection", "csrf",
    "injection",
    "privilege escalation",
    "red team",
    "defense", "defence",
    "hardening",
    "cybersecurity", "cyber security",
    "infosec",
    "security auditing", "security audit", "security tool",
    "cve", "cvss"
]

In [13]:
def make_pattern(keywords):
    parts = []
    for k in keywords:
        k_ = k.replace(" ", r"\s+")
        parts.append(r"\b" + k_ + r"\b")
    pattern = "(?:" + "|".join(parts) + ")"
    return pattern

In [14]:
ai_pattern = make_pattern(ai_keywords)
security_pattern = make_pattern(security_keywords)

In [15]:
df2['is_ai'] = df2['text_all'].str.contains(ai_pattern, regex=True, na=False)
df2['is_security'] = df2['text_all'].str.contains(security_pattern, regex=True, na=False)

df2['is_ai'].value_counts(), df2['is_security'].value_counts()

/tmp/ipykernel_683/1154363465.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['is_ai'] = df2['text_all'].str.contains(ai_pattern, regex=True, na=False)
/tmp/ipykernel_683/1154363465.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['is_security'] = df2['text_all'].str.contains(security_pattern, regex=True, na=False)

(is_ai
 False    1212
 True      848
 Name: count, dtype: int64,
 is_security
 False    1779
 True      281
 Name: count, dtype: int64)

In [16]:
df2['is_intersection'] = df2['is_ai'] & df2['is_security']
intersection_df = df2[df2['is_intersection']]

len(intersection_df), len(df2)

/tmp/ipykernel_683/443220505.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['is_intersection'] = df2['is_ai'] & df2['is_security']

(131, 2060)

In [17]:
intersection_df.duplicated(subset='name').sum()

np.int64(0)

In [18]:
intersection_df = df2[df2['is_intersection']].copy()

In [19]:
unique_df = intersection_df.drop_duplicates(subset='name', keep='first').reset_index(drop=True)

In [20]:
unique_df

,type,query,name,url,description,stars,language,date,text_all,is_ai,is_security,is_intersection
0,repository,"""open source"" ""AI"" ""secure"" stars:>50 in:name,...",daytonaio/daytona,https://github.com/daytonaio/daytona,Daytona is a Secure and Elastic Infrastructure...,37972.0,TypeScript,2025-12-17T15:00:02Z,daytonaio/daytona daytona is a secure and elas...,True,True,True
1,repository,"""open source"" ""AI"" ""secure"" stars:>50 in:name,...",danny-avila/LibreChat,https://github.com/danny-avila/LibreChat,"Enhanced ChatGPT Clone: Features Agents, MCP, ...",32487.0,TypeScript,2025-12-17T14:55:52Z,danny-avila/librechat enhanced chatgpt clone: ...,True,True,True
2,repository,"""open source"" ""AI"" ""security"" stars:>50 in:nam...",usestrix/strix,https://github.com/usestrix/strix,Open-source AI agents for penetration testing,17918.0,Python,2025-12-17T14:57:16Z,usestrix/strix open-source ai agents for penet...,True,True,True
3,repository,"""open source"" ""AI"" ""security"" stars:>50 in:nam...",microsoft/mcp-for-beginners,https://github.com/microsoft/mcp-for-beginners,This open-source curriculum introduces the fun...,13737.0,Jupyter Notebook,2025-12-17T12:29:14Z,microsoft/mcp-for-beginners this open-source c...,True,True,True
4,repository,"""open source"" ""AI"" ""security"" stars:>50 in:nam...",promptfoo/promptfoo,https://github.com/promptfoo/promptfoo,"Test your prompts, agents, and RAGs. AI Red te...",9457.0,TypeScript,2025-12-17T14:56:34Z,"promptfoo/promptfoo test your prompts, agents,...",True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
126,repository,"""open source"" ""AI"" ""threat"" stars:>50 in:name,...",82ch/MCP-Dandan,https://github.com/82ch/MCP-Dandan,MCP Security Solution for Agentic AI ‚Äî real-...,54.0,Python,2025-12-17T11:09:20Z,82ch/mcp-dandan mcp security solution for agen...,True,True,True
127,repository,"""open source"" ""LLM"" ""security"" stars:>50 in:na...",aomail-ai/aomail-app,https://github.com/aomail-ai/aomail-app,Aomail is an AI interface that connects to Gma...,54.0,Vue,2025-12-09T21:57:19Z,aomail-ai/aomail-app aomail is an ai interface...,True,True,True
128,repository,"""open source"" ""large language model"" ""security...",datasec-lab/CodeBreaker,https://github.com/datasec-lab/CodeBreaker,[USENIX Security '24] An LLM-Assisted Easy-to-...,53.0,Python,2025-11-18T01:23:09Z,datasec-lab/codebreaker [usenix security '24] ...,True,True,True
129,repository,"""open source"" ""machine learning"" ""secure"" star...",AI-secure/aug-pe,https://github.com/AI-secure/aug-pe,[ICML 2024 Spotlight] Differentially Private S...,52.0,Python,2025-12-10T22:32:18Z,ai-secure/aug-pe [icml 2024 spotlight] differe...,True,True,True
130,repository,"""open source"" ""large language model"" ""adversar...",user1342/Oversight,https://github.com/user1342/Oversight,"A Completely Modular LLM Reverse Engineering, ...",52.0,Python,2025-10-19T15:20:53Z,user1342/oversight a completely modular llm re...,True,True,True

In [21]:
unique_df['stars'] = unique_df['stars'].astype(int)

In [22]:
unique_df

,type,query,name,url,description,stars,language,date,text_all,is_ai,is_security,is_intersection
0,repository,"""open source"" ""AI"" ""secure"" stars:>50 in:name,...",daytonaio/daytona,https://github.com/daytonaio/daytona,Daytona is a Secure and Elastic Infrastructure...,37972,TypeScript,2025-12-17T15:00:02Z,daytonaio/daytona daytona is a secure and elas...,True,True,True
1,repository,"""open source"" ""AI"" ""secure"" stars:>50 in:name,...",danny-avila/LibreChat,https://github.com/danny-avila/LibreChat,"Enhanced ChatGPT Clone: Features Agents, MCP, ...",32487,TypeScript,2025-12-17T14:55:52Z,danny-avila/librechat enhanced chatgpt clone: ...,True,True,True
2,repository,"""open source"" ""AI"" ""security"" stars:>50 in:nam...",usestrix/strix,https://github.com/usestrix/strix,Open-source AI agents for penetration testing,17918,Python,2025-12-17T14:57:16Z,usestrix/strix open-source ai agents for penet...,True,True,True
3,repository,"""open source"" ""AI"" ""security"" stars:>50 in:nam...",microsoft/mcp-for-beginners,https://github.com/microsoft/mcp-for-beginners,This open-source curriculum introduces the fun...,13737,Jupyter Notebook,2025-12-17T12:29:14Z,microsoft/mcp-for-beginners this open-source c...,True,True,True
4,repository,"""open source"" ""AI"" ""security"" stars:>50 in:nam...",promptfoo/promptfoo,https://github.com/promptfoo/promptfoo,"Test your prompts, agents, and RAGs. AI Red te...",9457,TypeScript,2025-12-17T14:56:34Z,"promptfoo/promptfoo test your prompts, agents,...",True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
126,repository,"""open source"" ""AI"" ""threat"" stars:>50 in:name,...",82ch/MCP-Dandan,https://github.com/82ch/MCP-Dandan,MCP Security Solution for Agentic AI ‚Äî real-...,54,Python,2025-12-17T11:09:20Z,82ch/mcp-dandan mcp security solution for agen...,True,True,True
127,repository,"""open source"" ""LLM"" ""security"" stars:>50 in:na...",aomail-ai/aomail-app,https://github.com/aomail-ai/aomail-app,Aomail is an AI interface that connects to Gma...,54,Vue,2025-12-09T21:57:19Z,aomail-ai/aomail-app aomail is an ai interface...,True,True,True
128,repository,"""open source"" ""large language model"" ""security...",datasec-lab/CodeBreaker,https://github.com/datasec-lab/CodeBreaker,[USENIX Security '24] An LLM-Assisted Easy-to-...,53,Python,2025-11-18T01:23:09Z,datasec-lab/codebreaker [usenix security '24] ...,True,True,True
129,repository,"""open source"" ""machine learning"" ""secure"" star...",AI-secure/aug-pe,https://github.com/AI-secure/aug-pe,[ICML 2024 Spotlight] Differentially Private S...,52,Python,2025-12-10T22:32:18Z,ai-secure/aug-pe [icml 2024 spotlight] differe...,True,True,True
130,repository,"""open source"" ""large language model"" ""adversar...",user1342/Oversight,https://github.com/user1342/Oversight,"A Completely Modular LLM Reverse Engineering, ...",52,Python,2025-10-19T15:20:53Z,user1342/oversight a completely modular llm re...,True,True,True

In [25]:
unique_df.to_csv("github_filtered.csv", index=False)
from google.colab import files
files.download("github_filtered.csv")